import { Box } from "@mui/material";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "./frontend/components/shared/Footer";
import Navbar from "./frontend/components/shared/Navbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Box sx={{ minHeight: "100vh", maxWidth: "100%", overflow: "hidden" }}>
          {children}
        </Box>

        <Footer />
      </body>
    </html>
  );
}
